### ISSUE TITLE
Dependency conflict with psalm: incompatible versions of nikic/php-parser

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/openapi-extractor#129]
3ae4ad79bce2ca7a893e354741c1b3d41408dc06 breaks dependency resolution for me:

- vimeo/psalm 5.24.0 requires nikic/php-parser ^4.16
- nextcloud/openapi-extractor dev-main requires nikic/php-parser ^5.0

I *could* use psalm master, but I'm not sure if that's intended

**Comment by provokateurin** [comment]
Please use https://github.com/bamarni/composer-bin-plugin to separate these dependencies, then it will work.

**Comment by theCalcaholic** [comment]
Thank you, that works :)
