### ISSUE TITLE
Bug: Dollar sign in array key throws error

### ISSUE THREAD

**Issue by susnux** [nextcloud/openapi-extractor#139]
Given return type annotation:

```
@return array{foo: array{$comment: string, bar: bool}}
```

This will cause an error like:
> PHP Fatal error:  Uncaught Error: Capabilities.php: No return value
  thrown in openapi-extractor/src/Logger.php on line 42
> Script generate-spec handling the __exec_command event returned with error code 255

PHP code looks like this:

```php
return [
    'foo' => [
        '$comment' => 'Some comment in json schema style',
        'bar' => true,
    ]
];

**Comment by provokateurin** [comment]
Are you sure this is valid psalm syntax? I've never seen a dollar sign as an array key, but at least from the php side it shouldn't be forbidden I guess.

**Comment by provokateurin** [comment]
https://github.com/nextcloud/server/pull/46414 and in your PR it seems to work just fine? At least no CI failure and you were able to generate the spec?

**Comment by susnux** [comment]
Notice the workaround: I quoted the key (`'$comment'`)

**Comment by provokateurin** [comment]
This is a PHPStan problem we can not fix:
```
PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTagNode Object
(
    [name] => @return
    [value] => PHPStan\PhpDocParser\Ast\PhpDoc\InvalidTagValueNode Object
        (
            [value] => array{files: array{$comment: ?string, bigfilechunking: bool, blacklisted_files: array<mixed>, forbidden_filenames: list<string>, forbidden_filename_characters: list<string>, forbidden_filename_extensions: list<string>}}
            [exceptionArgs:PHPStan\PhpDocParser\Ast\PhpDoc\InvalidTagValueNode:private] => Array
                (
                    [0] => :
                    [1] => 31
                    [2] => 68
                    [3] => 34
                    [4] => 
                    [5] => 4
                )

            [attributes:PHPStan\PhpDocParser\Ast\PhpDoc\InvalidTagValueNode:private] => Array
                (
                )

        )

    [attributes:PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTagNode:private] => Array
        (
        )

)
```
This is the node I get when unquoting the dollar sign. You  will simply have to use the quotes as there is nothing we can do here.

**Comment by susnux** [comment]
@provokateurin should we report this upstream then?

**Comment by provokateurin** [comment]
Could be worth a try, can you do that?

**Comment by susnux** [comment]
> Could be worth a try, can you do that?

https://github.com/phpstan/phpstan/issues/11326
