### ISSUE TITLE
App without any routes generates no openapi.json despite having schemas

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/openapi-extractor#79]
This broke with https://github.com/nextcloud/openapi-extractor/pull/24.
The comments app in server is affected, because it has no routes and only it's capabilities are present (deleted the openapi.json file, it will not be regenerated).

**Comment by nickvergessen** [comment]
Well why should it generate schemas that are not used anywhere? But yeah I also noticed it and wondered why it gets a file at all. Should be only for the capabilities. But the schemas must be removed as they are not used

**Comment by nickvergessen** [comment]
But yeah, fix will come that we generate default when capabilities are there even without any route

**Comment by provokateurin** [comment]
Capabilities is the only reason why we need this, any other case indicates a problem with the app.
