### ISSUE TITLE
Support body parameters

### ISSUE THREAD

**Issue by come-nc** [nextcloud/openapi-extractor#88]
Hello,

I’m not exactly sure how to decide/detect this, but currently all parameters get documented as in query: `"in": "query",`

While in our case we expect those in the JSON body of the PUT.
This is a problem when using tools to generate documentation based on the openapi.json file.

**Comment by provokateurin** [comment]
I hope I can put some work into this soonish as it also stops people from using type aliases for parameter types

**Comment by provokateurin** [comment]
Instead of making a flag to turn all parameters into body parameters all the time we could use the new attribute for it to change it for single endpoints/controllers.
